### ISSUE TITLE
Method TTGateway.connect crashes the app

### ISSUE THREAD

**Issue by unishienga** [ttlock/ttlock_flutter#40]
When sending method TTGateway.connect using Flutter SDK, it causes my application to crash.

Here is how the method is called

`TTGateway.connect(gateway.gatewayMac, (status) {
      if (status == TTGatewayConnectStatus.success) {
        gatewayModelProvider.updateCanInit(true);
      } else {
        gatewayModelProvider.updateIsLoading(false);
        scaffoldMessage.showSnackBar(
            const SnackBar(content: Text("Error to connect gateway!")));
      }
    });`

Here is the log returned

`D/a       (29208): a(L:36) - bluetooth is prepared
D/WirelessDoorSensorClient(29208): prepareBTService(L:1) - prepare service
D/BaseGattCallbackHelper(29208): prepare(L:3) - context:com.example.shienga_smart_app.MainActivity@146f3cb
D/BaseGattCallbackHelper(29208): prepare(L:4) - mBluetoothAdapter:android.bluetooth.BluetoothAdapter@c2da48b
D/OMG     (29208): ==connect2Device=
D/a       (29208): a(L:16) - connect_status:1
I/BluetoothAdapter(29208): STATE_ON
D/BluetoothGatt(29208): connect() - device: 486762_8, auto: false
D/BluetoothGatt(29208): registerApp()
D/BluetoothGatt(29208): registerApp() - UUID=58da10ea-434a-4aff-bddf-36a7a1755322
D/BluetoothGatt(29208): onClientRegistered() - status=0 clientIf=6
D/BluetoothGatt(29208): onClientConnectionState() - status=0 clientIf=6 device=486762_8
D/GattCallbackHelper(29208): onConnectionStateChange(L:13) - STATE_CONNECTED
D/BluetoothGatt(29208): discoverServices() - device: 486762_8
D/GattCallbackHelper(29208): onConnectionStateChange(L:14) - Attempting to start service discovery:true
D/BluetoothGatt(29208): onConnectionUpdated() - Device=486762_8 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(29208): onSearchComplete() = Device=486762_8 Status=0
D/GattCallbackHelper(29208): onServicesDiscovered(L:2) -
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:00001800-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:00001801-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:00001911-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:0000180f-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:0000180a-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:7) - service:73631912-6965-6e65-7269-736669727374
D/GattCallbackHelper(29208): onServicesDiscovered(L:15) - 00002a29-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:16) - read characteristic:Thread[binder:29208_2,5,main]
D/GattCallbackHelper(29208): onServicesDiscovered(L:15) - 00002a24-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:16) - read characteristic:Thread[binder:29208_2,5,main]
D/GattCallbackHelper(29208): onServicesDiscovered(L:15) - 00002a27-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:16) - read characteristic:Thread[binder:29208_2,5,main]
D/GattCallbackHelper(29208): onServicesDiscovered(L:15) - 00002a26-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:16) - read characteristic:Thread[binder:29208_2,5,main]
D/GattCallbackHelper(29208): onServicesDiscovered(L:15) - 00002a25-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onServicesDiscovered(L:16) - read characteristic:Thread[binder:29208_2,5,main]
D/GattCallbackHelper(29208): onCharacteristicRead(L:2) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@7a3ddaa status=0
D/GattCallbackHelper(29208): onCharacteristicRead(L:2) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@9cb5d9b status=0
D/BluetoothGatt(29208): onConnectionUpdated() - Device=486762_8 interval=39 latency=0 timeout=500 status=0
D/GattCallbackHelper(29208): onCharacteristicRead(L:2) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@2fe4538 status=0
D/GattCallbackHelper(29208): onCharacteristicRead(L:2) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@aab911 status=0
D/GattCallbackHelper(29208): onCharacteristicRead(L:21) - deviceInfo:DeviceInfo{modelNum='SN344', hardwareRevision='1.10', firmwareRevision='6.0.0.231007', networkMac='f8:A5:B0:62:67:48'}
D/GattCallbackHelper(29208): onCharacteristicRead(L:28) - 00000003-0000-1000-8000-00805f9b34fb
D/BluetoothGatt(29208): setCharacteristicNotification() - uuid: 00000003-0000-1000-8000-00805f9b34fb enable: true
D/GattCallbackHelper(29208): onCharacteristicRead(L:36) - writeDescriptor successed
D/GattCallbackHelper(29208): onCharacteristicRead(L:28) - 00000002-0000-1000-8000-00805f9b34fb
D/GattCallbackHelper(29208): onDescriptorWrite(L:4) - 
D/Command (29208): getAeskey(L:4) - getAeskey macBytes:[f8,a5,b0,62,67,48]
D/Command (29208): getAeskey(L:6) - getAeskey aeskey:[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
D/Command (29208): setData(L:2) - data=[53,43,49,45,4e,45,52]
D/Command (29208): setData(L:3) - aesKeyArray=[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
I/tag     (29208): 初始化本地jni代码
D/GattCallbackHelper(29208): sendCommand(L:3) - send datas:[72,5b,45,10,81,92,95,40,f5,8a,d4,9f,c8,bc,fd,fa,db,d8,1d,0d,87]
D/GattCallbackHelper(29208): onCharacteristicWrite(L:5) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@13a2a76 status=0
D/GattCallbackHelper(29208): onCharacteristicWrite(L:5) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@13a2a76 status=0
D/GattCallbackHelper(29208): onCharacteristicChanged(L:2) - 
D/GattCallbackHelper(29208): onCharacteristicChanged(L:7) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@bf83877
D/GattCallbackHelper(29208): onCharacteristicChanged(L:9) - data:[72,5b,45,10,94,34,9b,17,ff,d0,05,5c,66,89,4a,d9,e5,46,ad,30]
D/GattCallbackHelper(29208): onCharacteristicChanged(L:14) - recDataTotalLen:21
D/GattCallbackHelper(29208): onCharacteristicChanged(L:21) - hasRecDataLen:20
D/GattCallbackHelper(29208): onCharacteristicChanged(L:2) -
D/GattCallbackHelper(29208): onCharacteristicChanged(L:7) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@bf83877
D/GattCallbackHelper(29208): onCharacteristicChanged(L:9) - data:[97]
D/GattCallbackHelper(29208): onCharacteristicChanged(L:21) - hasRecDataLen:21
D/GattCallbackHelper(29208): onCharacteristicChanged(L:23) - recDataTotalLen:21
D/GattCallbackHelper$d(29208): run(L:1) - values:[72,5b,45,10,94,34,9b,17,ff,d0,05,5c,66,89,4a,d9,e5,46,ad,30,97]
D/Command (29208): getAeskey(L:4) - getAeskey macBytes:[f8,a5,b0,62,67,48]
D/Command (29208): getAeskey(L:6) - getAeskey aeskey:[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
D/GattCallbackHelper$d(29208): run(L:5) - command:45
D/GattCallbackHelper$d(29208): run(L:6) - data:[00,f8,a5,b0,62,67,48]
D/a       (29208): a(L:16) - connect_status:2
D/OMG     (29208): ====disconnect==1==
I/flutter (29208): TTLock listen: {data: {status: 1}, resultState: 0, command: connectGateway}
Another exception was thrown: setState() or markNeedsBuild() called during build.
D/a       (29208): a(L:36) - bluetooth is prepared
D/WirelessDoorSensorClient(29208): prepareBTService(L:1) - prepare service
D/BaseGattCallbackHelper(29208): prepare(L:3) - context:com.example.shienga_smart_app.MainActivity@146f3cb
D/BaseGattCallbackHelper(29208): prepare(L:4) - mBluetoothAdapter:android.bluetooth.BluetoothAdapter@c2da48b
D/a       (29208): a(L:16) - connect_status:2
D/d       (29208): a(L:17) - plugversion:1
D/Command (29208): getAeskey(L:4) - getAeskey macBytes:[f8,a5,b0,62,67,48]
D/Command (29208): getAeskey(L:6) - getAeskey aeskey:[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
D/Command (29208): setData(L:2) - data=[0f,70,6c,75,67,2e,73,63,69,65,6e,65,72,2e,63,6e,0b,b7]
D/Command (29208): setData(L:3) - aesKeyArray=[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
D/GattCallbackHelper(29208): sendCommand(L:3) - send datas:[72,5b,03,20,8a,ea,12,9e,d4,65,5a,14,a0,66,01,eb,f7,1d,37,a9,10,be,91,e6,9a,82,10,26,8e,74,d0,d8,3e,73,c5,e6,08]
D/GattCallbackHelper(29208): onCharacteristicWrite(L:5) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@13a2a76 status=0
D/GattCallbackHelper(29208): onCharacteristicWrite(L:5) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@13a2a76 status=0
D/GattCallbackHelper(29208): onCharacteristicChanged(L:2) - 
D/GattCallbackHelper(29208): onCharacteristicChanged(L:7) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@bf83877
D/GattCallbackHelper(29208): onCharacteristicChanged(L:9) - data:[72,5b,03,10,5a,fb,9f,af,94,c7,08,46,8d,0f,64,3a,86,8c,ba,76]
D/GattCallbackHelper(29208): onCharacteristicChanged(L:14) - recDataTotalLen:21
D/GattCallbackHelper(29208): onCharacteristicChanged(L:21) - hasRecDataLen:20
D/GattCallbackHelper(29208): onCharacteristicChanged(L:2) -
D/GattCallbackHelper(29208): onCharacteristicChanged(L:7) - gatt=android.bluetooth.BluetoothGatt@8732895 characteristic=android.bluetooth.BluetoothGattCharacteristic@bf83877
D/GattCallbackHelper(29208): onCharacteristicChanged(L:9) - data:[d8]
D/GattCallbackHelper(29208): onCharacteristicChanged(L:21) - hasRecDataLen:21
D/GattCallbackHelper(29208): onCharacteristicChanged(L:23) - recDataTotalLen:21
D/GattCallbackHelper$d(29208): run(L:1) - values:[72,5b,03,10,5a,fb,9f,af,94,c7,08,46,8d,0f,64,3a,86,8c,ba,76,d8]
D/Command (29208): getAeskey(L:4) - getAeskey macBytes:[f8,a5,b0,62,67,48]
D/Command (29208): getAeskey(L:6) - getAeskey aeskey:[1b,b5,94,12,50,fb,5f,c2,2b,00,32,ee,ec,ae,e7,60]
D/GattCallbackHelper$d(29208): run(L:5) - command:03
D/GattCallbackHelper$d(29208): run(L:6) - data:[00]
D/AndroidRuntime(29208): Shutting down VM
E/AndroidRuntime(29208): FATAL EXCEPTION: main
E/AndroidRuntime(29208): Process: com.example.shienga_smart_app, PID: 29208
E/AndroidRuntime(29208): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime(29208):        at java.lang.StringBuilder.<init>(StringBuilder.java:113)
E/AndroidRuntime(29208):        at com.ttlock.bl.sdk.gateway.model.ConfigureGatewayInfo.getCorrentNameBytes(SourceFile:1)
E/AndroidRuntime(29208):        at com.ttlock.bl.sdk.gateway.command.CommandUtil.configureAccount(SourceFile:5)
E/AndroidRuntime(29208):        at com.ttlock.bl.sdk.gateway.api.GattCallbackHelper$d.run(SourceFile:122)
E/AndroidRuntime(29208):        at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(29208):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29208):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(29208):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(29208):        at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(29208):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29208):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(29208):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process (29208): Sending signal. PID: 29208 SIG: 9`

**Comment by Sameer330** [comment]
Got any solution for this? We faced a similar issue with initSdk function.

`ttlock_flutter: ^0.3.6`

E/AndroidRuntime(30158): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ttlock/bl/sdk/keypad/WirelessKeypadClient;
E/AndroidRuntime(30158):        at com.ttlock.ttlock_flutter.TtlockFlutterPlugin.initSdk(TtlockFlutterPlugin.java:286)
E/AndroidRuntime(30158):        at com.ttlock.ttlock_flutter.TtlockFlutterPlugin.onMethodCall(TtlockFlutterPlugin.java:262)
E/AndroidRuntime(30158):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(30158):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(30158):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
