### ISSUE TITLE
Method TTLock.initLock crashes the app

### ISSUE THREAD

**Issue by morgan-rozza** [ttlock/ttlock_flutter#42]
app crash when add lock in android 10 & 11 only
Code
TTLock.initLock(map, (lockData) {
                                                    this.lockData = lockData;
                                                  }, (errorCode, errorMsg) {
                                                  showToast(context: context,msg: getTtLockMessage(context,errorCode,errorMsg),
                                                        type: DialogType.WARNING);
                                                  },);
debug
W/AESUtil ( 6534): Encrypt(L:٥) - the length of Key is not 16
D/AndroidRuntime( 6534): Shutting down VM
E/AndroidRuntime( 6534): FATAL EXCEPTION: main
E/AndroidRuntime( 6534): Process: com.softzone.e_pro, PID: 6534
E/AndroidRuntime( 6534): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 6534): 	at android.util.Base64.encode(Base64.java:495)
E/AndroidRuntime( 6534): 	at android.util.Base64.encodeToString(Base64.java:457)
E/AndroidRuntime( 6534): 	at com.ttlock.bl.sdk.api.b.a(SourceFile:311)
E/AndroidRuntime( 6534): 	at com.ttlock.bl.sdk.api.f.a(SourceFile:134)
E/AndroidRuntime( 6534): 	at com.ttlock.bl.sdk.api.a$e.run(SourceFile:17249)
E/AndroidRuntime( 6534): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6534): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6534): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6534): 	at android.app.ActivityThread.main(ActivityThread.java:7386)
E/AndroidRuntime( 6534): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6534): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6534): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
I/Process ( 6534): Sending signal. PID: 6534 SIG: 9
Lost connection to device.

**Comment by darssh26** [comment]
I encountered this issue only on Android when the device locale is Arabic so the solution is to force the English locale in the MainActivity.kt like this:
`
import android.os.Bundle
import java.util.Locale
import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Locale.setDefault(Locale.ENGLISH)
    }
}
`

**Comment by morgan-rozza** [comment]
thanks it works fine

**Comment by morgan-rozza** [comment]
> I encountered this issue only on Android when the device locale is Arabic so the solution is to force the English locale in the **MainActivity.kt** like this:
> 
> import android.os.Bundle import java.util.Locale import io.flutter.embedding.android.FlutterActivity
> 
> class MainActivity : FlutterActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState) Locale.setDefault(Locale.ENGLISH) } }

it works fine thank you
