### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ttlock/bl/sdk/api/TTLockClient

### ISSUE THREAD

**Issue by mohitleo03** [ttlock/ttlock_flutter#44]
While Using TTLock.controlLock function the app is crashing.

Logs ->

FATAL EXCEPTION: main
E/AndroidRuntime(31633): Process: com.dhanuka.safeobuddy, PID: 31633
E/AndroidRuntime(31633): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ttlock/bl/sdk/api/TTLockClient;
E/AndroidRuntime(31633): 	at com.ttlock.ttlock_flutter.TtlockFlutterPlugin.initSdk(TtlockFlutterPlugin.java:283)
E/AndroidRuntime(31633): 	at com.ttlock.ttlock_flutter.TtlockFlutterPlugin.onMethodCall(TtlockFlutterPlugin.java:262)
E/AndroidRuntime(31633): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(31633): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(31633): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(31633): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(31633): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(31633): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31633): 	at android.os.Looper.loopOnce(Looper.java:224)
E/AndroidRuntime(31633): 	at android.os.Looper.loop(Looper.java:318)
E/AndroidRuntime(31633): 	at android.app.ActivityThread.main(ActivityThread.java:8772)
E/AndroidRuntime(31633): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31633): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
E/AndroidRuntime(31633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime(31633): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ttlock.bl.sdk.api.TTLockClient" on path: DexPathList[[zip file "/data/app/~~prSmkvUVfHsYGUQMq4qL-Q==/com.dhanuka.safeobuddy-T4JkeUlANTKFq6Z_3wrnew==/base.apk"],nativeLibraryDirectories=[/data/app/~~prSmkvUVfHsYGUQMq4qL-Q==/com.dhanuka.safeobuddy-T4JkeUlANTKFq6Z_3wrnew==/lib/arm64, /data/app/~~prSmkvUVfHsYGUQMq4qL-Q==/com.dhanuka.safeobuddy-T4JkeUlANTKFq6Z_3wrnew==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(31633): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(31633): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
E/AndroidRuntime(31633): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
E/AndroidRuntime(31633): 	... 14 more
W/nuka.safeobuddy(31633): type=1400 audit(0.0:201019): avc:  denied  { search } for  name="miuilog" dev="dm-60" ino=367 scontext=u:r:untrusted_app_32:s0:c144,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.dhanuka.safeobuddy
W/nuka.safeobuddy(31633): type=1400 audit(0.0:201020): avc:  denied  { search } for  name="miuilog" dev="dm-60" ino=367 scontext=u:r:untrusted_app_32:s0:c144,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.dhanuka.safeobuddy
W/nuka.safeobuddy(31633): type=1400 audit(0.0:201021): avc:  denied  { search } for  name="miuilog" dev="dm-60" ino=367 scontext=u:r:untrusted_app_32:s0:c144,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.dhanuka.safeobuddy
W/nuka.safeobuddy(31633): type=1400 audit(0.0:201022): avc:  denied  { search } for  name="miuilog" dev="dm-60" ino=367 scontext=u:r:untrusted_app_32:s0:c144,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.dhanuka.safeobuddy

W/nuka.safeobuddy(31633): type=1400 audit(0.0:201023): avc:  denied  { search } for  name="miuilog" dev="dm-60" ino=367 scontext=u:r:untrusted_app_32:s0:c144,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.dhanuka.safeobuddy
W/ScoutUtils(31633): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
I/Process (31633): Process is going to kill itself!
I/Process (31633): java.lang.Exception
I/Process (31633): 	at android.os.Process.killProcess(Process.java:1363)
I/Process (31633): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:174)
I/Process (31633): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process (31633): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process (31633): 	at io.flutter.embedding.engine.dart.DartMessenger.handleError(DartMessenger.java:419)
I/Process (31633): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:300)
I/Process (31633): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/Process (31633): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/Process (31633): 	at android.os.Handler.handleCallback(Handler.java:958)
I/Process (31633): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/Process (31633): 	at android.os.Looper.loopOnce(Looper.java:224)
I/Process (31633): 	at android.os.Looper.loop(Looper.java:318)
I/Process (31633): 	at android.app.ActivityThread.main(ActivityThread.java:8772)
I/Process (31633): 	at java.lang.reflect.Method.invoke(Native Method)
I/Process (31633): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
I/Process (31633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/Process (31633): Sending signal. PID: 31633 SIG: 9
Lost connection to device.

Exited.

Our Code ->
    TTLock.printLog = true;
    TTLock.controlLock(lockData, TTControlAction.unlock,
        (lockTime, electricQuantity, uniqueId) {
         //handling success
    }, (TTLockError errorCode, errorMsg) async {
         //handling error
    });
@JLGB @ttlock

**Comment by Sameer330** [comment]
Did you find any solution to this?
Which version of the package were you using before this occurred??
