### ISSUE TITLE
TTLock.modifyAdminPasscode : type '() => Null' is not a subtype of type '(String) => void'

### ISSUE THREAD

**Issue by SDS712** [ttlock/ttlock_flutter#9]
Code Snippet of the function from example app that was invoked :
```
case Command.modifyAdminPasscode:
        TTLock.modifyAdminPasscode('1234', lockData, () {
          _showSuccessAndDismiss("Success");
        }, (errorCode, errorMsg) {
          _showErrorAndDismiss(errorCode, errorMsg);
        });
        break;
```

Error :
```
E/flutter (28672): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type '() => Null' is not a subtype of type '(String) => void'
E/flutter (28672): #0      TTLock._successCallback
E/flutter (28672): #1      TTLock._onEvent
E/flutter (28672): #2      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (28672): #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (28672): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (28672): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (28672): #6      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (28672): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (28672): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (28672): #9      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (28672): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (28672): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (28672): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (28672): #13     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (28672): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (28672): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (28672): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (28672): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (28672): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

Seems like `TTLockClient.getDefault().modifyAdminPasscode` expects `onModifyAdminPasscodeSuccess` callback but  `TTSuccessCallback` with a different signature was given in `TTLock.modifyAdminPasscode`.

```
public void setAdminPasscode(final TtlockModel ttlockModel) {
    TTLockClient.getDefault().modifyAdminPasscode(ttlockModel.adminPasscode, ttlockModel.lockData, ttlockModel.lockMac, new ModifyAdminPasscodeCallback() {
      @Override
      public void onModifyAdminPasscodeSuccess(String passcode) {
        ttlockModel.adminPasscode = passcode;
        apiSuccess(ttlockModel);
      }

      @Override
      public void onFail(LockError lockError) {
        apiFail(lockError);
      }
    });
  }
```

```
static void modifyAdminPasscode(String adminPasscode, String lockData,
      TTSuccessCallback callback, TTFailedCallback failedCallback) {
    Map map = Map();
    map[TTResponse.adminPasscode] = adminPasscode;
    map[TTResponse.lockData] = lockData;
    invoke(COMMAND_MODIFY_ADMIN_PASSCODE, map, callback, fail: failedCallback);
  }
```

**Comment by zjut019** [comment]
I have test the api, it can work fine.Maybe you can try again with the latest version.
